---
- name: Install ISS
  hosts: all
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes