
name: Bump version
on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version pre-stage"
        required: false
        default: "0.0.0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Config
        run: |
          pip install -U git-semver
          git config --global user.email "pipeline@withleaf.io"
          git config --global user.name "{{ github.repository_owner }}"
          git fetch --all
          git fetch --tags
      - name: Create Tag
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |   
          TAG=""

          if [ $(git tag | wc -l) -gt 0 ]; then
            if [ $(git log -1 --pretty=%B | grep -E ^feature\: | wc -l) -gt 0 ]; then 
              TAG=$(git semver --next-minor) 
            elif [ $(git log -1 --pretty=%B | grep -E ^breaking\: | wc -l) -gt 0 ]; then 
              TAG=$(git semver --next-major)
            else
              TAG=$(git semver --next-patch)
            fi
            echo "Creating tag: "$TAG
          else
            echo "No tags found. Creating tag: ${{ github.event.inputs.version }}"
            TAG=${{ github.event.inputs.version }}
          fi
          git tag -a $TAG -m "$(git log -1 --pretty=%B)"
          git push --tags

