
name: Bump version
on: 
  workflow_dispatch:
    inputs:
      semantic:
        description: "Semantic version: (patch, minor, major)"
        required: true
        default: "patch"
  push:
    branches:
      - dev
      - stg
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Config
        run: |
          pip install semver
          git config --global user.email "tiago.matana@gmail.com"
          git config --global user.name "Tiago Matana"
      - name: Create Tag
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |   
          git fetch --tags
          TAG=""
          SEMANTIC=${{ github.event.inputs.semantic }}
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          BRANCH=$(git branch --show-current)

          case $BRANCH in
            dev)
              if [ $(echo $VERSION | grep -E "rc" | wc -l) -gt 0]; then
                VERSION=$(pysemver nextver $VERSION $SEMANTIC)
              fi
              TAG=$(pysemver bump build $VERSION)
              ;;
            stg)
              if [ $(echo $VERSION | grep -E "build" | wc -l) -gt 0]; then
                VERSION=$(pysemver nextver $VERSION $SEMANTIC)
              fi
              TAG=$(pysemver bump prerelease $VERSION)
              ;;
            master)
              TAG=$(pysemver bump $SEMANTIC $VERSION)
              ;;
            *)
              echo "No tags found. Creating tag: 0.0.1"
              TAG="0.0.1"
              ;;
          esac
              
          git tag -a $TAG -m "$(git log -1 --pretty=%B)"
          git push --tags

