
name: Bump version
on: 
  workflow_dispatch:
    inputs:
      semantic:
        description: "Semantic version: (patch, minor, major)"
        required: true
        default: "patch"
  push:
    branches:
      - dev
      - stg
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Config
        run: |
          pip install -U git-semver
          pip install -U semver
          git config --global user.email "pipeline@withleaf.io"
          git config --global user.name "Leaf"
          git fetch --all
          git fetch --tags
      - name: Create Tag
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |   
          TAG=""
          SEMANTIC=${{ github.event.inputs.semantic }}
          VERSION=$(git describe --tags --abbrev=0)

          if [ $(git tag | wc -l) -gt 0 ]; then
            if [ $(git branch | grep -E master | wc -l) -gt 0 ]; then 
              TAG=$(pysemver bump $SEMANTIC $VERSION) 
            elif [ $(git branch | grep -E stg | wc -l) -gt 0 ]; then 
              TAG=$(pysemver bump prerelease $VERSION)
            else
              TAG=$(pysemver bump build $VERSION)
            fi
            echo "Creating tag: "$TAG
          else
            echo "No tags found. Creating tag: 0.0.1"
            TAG="0.0.1"
          fi
          git tag -a $TAG -m "$(git log -1 --pretty=%B)"
          git push --tags

