
name: Bump version
on: 
  workflow_dispatch:
    inputs:
      semantic:
        description: "Semantic version: (patch, minor, major)"
        required: true
        default: "patch"
      tag:
        description: "tag name"
        required: false
        default: ""
  push:
    branches:
      - stg
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Config
        run: |
          pip install semver
          git config --global user.email "tiago.matana@gmail.com"
          git config --global user.name "Tiago Matana"
      - name: Creating Tag
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |   
          git fetch --tags
          TAG=${{ github.event.inputs.tag }}
          SEMANTIC=${{ github.event.inputs.semantic }}
          VERSION="0.0.0"
          if [ $(git tag -l | wc -l) -gt 0 ]; then
            VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          fi
          BRANCH=$(git branch --show-current)

          case $BRANCH in
            stg)
              if [ $(echo $VERSION | grep -E "build" | wc -l) -gt 0 ]; then
                VERSION=$(pysemver nextver $VERSION $SEMANTIC)
              fi
              TAG=$(pysemver bump prerelease $VERSION)
              ;;
            master)
              TAG=$(pysemver bump $SEMANTIC $VERSION)
              ;;
            *)
              echo "Create tag $TAG in $BRANCH"

              ;;
          esac
              
          git tag -a $TAG -m "$(git log -1 --pretty=%B)"
          git push --tags

